name: Build Android APK
on: push
jobs:
  build_android:
    name: Build Android APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.19.5

      - name: add .env file
        run: echo "NEWS_API_KEY=${{ secrets.NEWS_API_KEY }}" >> .env

      - name: Pub clean
        run: flutter clean

      - name: Pub Get
        run: flutter pub get

      - name: Build apk
        run: flutter build apk --release

      - name: Delete .env file
        run: rm .env

  APK_upload:
    name: Build Android APK
    runs-on: ubuntu-latest
    needs: build_android
    steps:
      - name: APK upload
        uses: actions/upload-artifact@v4
        with:
          name: android-build
          path: build/app/outputs/flutter-apk/app-release.apk

  upload_to_app_center:
    name: Upload to AppCenter
    runs-on: ubuntu-latest
    needs: build_android
    steps:
      - name: Upload to AppCenter # The App Center Distribute Action
        run: |
          chmod +x upload-to-app-center.sh
          ./upload-to-app-center.sh -o saurabh.sonar120-gmail.com -a News-App -t ${{ secrets.APP_CENTER_TOKEN }} -f build/app/outputs/flutter-apk/app-release.apk