name: Build Android APK
on: push
jobs:
  build_android:
    name: Build Android APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.19.5

      - name: Pub clean
        run: flutter clean

      - name: Pub Get
        run: flutter pub get

      - name: Build apk
        run: flutter build apk --release

      - name: APK upload
        uses: actions/upload-artifact@v4
        with:
          name: android-build
          path: build/app/outputs/flutter-apk/app-release.apk

