name: Build Android APK and Upload to App Center by version tag
on:
  push:
    tags: # This section triggers the workflow on tag pushes (and creations)
      - v[0-9]+.[0-9]+.[0-9]+  # Matches tags like v1.2.3 (optional: adjust the pattern)
jobs:
  build_android:
    name: Build Android APK
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo github.event.pull_request.merged == true : ${{github.event.pull_request.merged == true}}
          echo github.event.pull_request.base.ref : ${{github.event.pull_request.base.ref}}
          echo github.event.ref : ${{github.event.ref}}
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.19.5

      - name: add .env file
        run: echo "NEWS_API_KEY=${{ secrets.NEWS_API_KEY }}" >> .env

      - name: Pub clean
        run: flutter clean

      - name: Pub Get
        run: flutter pub get

      - name: Build apk
        run: flutter build apk --release

      - name: Delete .env file
        run: rm .env

      - name: APK upload
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts.apk  # Include PR number in name
          path: build/app/outputs/flutter-apk/app-release.apk

      - uses: actions/download-artifact@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'v20.12.2'

      - name: Update npm packages
        run: |
          npm install formidable@latest
          npm install superagent@latest

      - name: Install app center
        run: npm install -g appcenter-cli

      - name: Upload APK to App Center
        run: appcenter distribute release -f build/app/outputs/flutter-apk/app-release.apk -a saurabh.sonar120-gmail.com/News-App --group Public --token ${{secrets.APP_CENTER_TOKEN}}
