name: Deploy App Center
on:
  pull_request:
    types: [ closed ]

jobs:
  deploy-app-center:
    name: Deply on App Center
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true # && github.event.pull_request.base.ref == 'master'  # Only run for PRs targeting master  # Only run this job on PR merge
    steps:
      - uses: build-apk.yml
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'v20.12.2'

      - name: Update npm packages
        run: |
          npm install formidable@latest
          npm install superagent@latest

      - name: Install app center
        run: npm install -g appcenter-cli

      - name: Upload APK to App Center
        run: appcenter distribute release -f build/app/outputs/flutter-apk/app-release.apk -a saurabh.sonar120-gmail.com/News-App --group Public --token ${{secrets.APP_CENTER_TOKEN}}
